JobType = {
  "B" : "Backup Job",
  "M" : "Migrated Job",
  "V" : "Verify Job",
  "R" : "Restore Job",
  "C" : "Console program (not in database)",
  "I" : "Internal or system Job",
  "D" : "Admin Job",
  "A" : "Archive Job (not implemented)",
  "C" : "Copy Job",
  "M" : "Migration Job",
}

JobStatus = {
  "C" : "Created but not yet running",
  "R" : "Running",
  "B" : "Blocked",
  "T" : "Terminated normally",
  "W" : "Terminated normally with warnings",
  "E" : "Terminated in Error",
  "e" : "Non-fatal error",
  "f" : "Fatal error",
  "D" : "Verify Differences",
  "A" : "Canceled by the user",
  "I" : "Incomplete Job",
  "F" : "Waiting on the File daemon",
  "S" : "Waiting on the Storage daemon",
  "m" : "Waiting for a new Volume to be mounted",
  "M" : "Waiting for a Mount",
  "s" : "Waiting for Storage resource",
  "j" : "Waiting for Job resource",
  "c" : "Waiting for Client resource",
  "d" : "Wating for Maximum jobs",
  "t" : "Waiting for Start Time",
  "p" : "Waiting for higher priority job to finish",
  "i" : "Doing batch insert file records",
  "a" : "SD despooling attributes",
  "l" : "Doing data despooling",
  "L" : "Committing data (last despool)"
}
