#!/usr/bin/env python3
"""Generate docker/initdb/02_seed.sql with absolute timestamps.

Usage:
    python scripts/generate_seed.py
    docker compose down -v && docker compose up --build
"""
from datetime import datetime, timedelta, timezone
import os
import sys

now = datetime.now(timezone.utc).replace(microsecond=0, tzinfo=None)
OUT = os.path.join(os.path.dirname(__file__), '..', 'docker', 'initdb', '02_seed.sql')


def ts(days=0, hours=0, minutes=0, forward=False):
    delta = timedelta(days=days, hours=hours, minutes=minutes)
    t = now + delta if forward else now - delta
    return t.strftime('%Y-%m-%d %H:%M:%S')


lines = []


def w(s=''):
    lines.append(s)


w('-- Bacula test seed data')
w('-- Generated by scripts/generate_seed.py — do NOT edit by hand')
w(f'-- Generated at: {now.strftime("%Y-%m-%d %H:%M:%S")} UTC')
w()

# ── Status codes ──────────────────────────────────────────────────────────────
w('-- ─── Status codes ──────────────────────────────────────────────────────────')
w("INSERT INTO status (jobstatus, jobstatuslong, severity) VALUES")
statuses = [
    ('C', 'Created but not yet running',             15),
    ('R', 'Running',                                 15),
    ('B', 'Blocked',                                 15),
    ('T', 'Terminated normally',                     10),
    ('W', 'Terminated normally with warnings',       20),
    ('E', 'Terminated in Error',                     25),
    ('e', 'Non-fatal error',                         20),
    ('f', 'Fatal error',                            100),
    ('D', 'Verify Differences',                      15),
    ('A', 'Canceled by the user',                    15),
    ('I', 'Incomplete Job',                          15),
    ('F', 'Waiting on the File daemon',              15),
    ('S', 'Waiting on the Storage daemon',           15),
    ('m', 'Waiting for a new Volume to be mounted',  15),
    ('M', 'Waiting for a Mount',                     15),
    ('s', 'Waiting for Storage resource',            15),
    ('j', 'Waiting for Job resource',                15),
    ('c', 'Waiting for Client resource',             15),
    ('d', 'Waiting for Maximum jobs',                15),
    ('t', 'Waiting for Start Time',                  15),
    ('p', 'Waiting for higher priority job',         15),
    ('i', 'Doing batch insert file records',         15),
    ('a', 'SD despooling attributes',                15),
    ('l', 'Doing data despooling',                   15),
    ('L', 'Committing data (last despool)',           15),
]
for i, (code, label, sev) in enumerate(statuses):
    comma = ',' if i < len(statuses) - 1 else ';'
    w(f"('{code}', '{label}', {sev}){comma}")
w()

# ── Clients ───────────────────────────────────────────────────────────────────
w('-- ─── Clients ───────────────────────────────────────────────────────────────')
w("INSERT INTO client (name, uname, autoprune, fileretention, jobretention) VALUES")
clients = [
    ('web-server.example.com',   'Linux x86_64 9.4.2 (01Jan22)'),
    ('db-server.example.com',    'Linux x86_64 9.4.2 (01Jan22)'),
    ('files-server.example.com', 'Linux x86_64 9.4.2 (01Jan22)'),
    ('app-server.example.com',   'Linux x86_64 9.4.2 (01Jan22)'),
]
for i, (name, uname_suffix) in enumerate(clients):
    comma = ',' if i < len(clients) - 1 else ';'
    w(f"('{name}', '{name}-fd {uname_suffix}', 1, 1209600, 2592000){comma}")
w()

# ── Storage / MediaType / Device ──────────────────────────────────────────────
w('-- ─── Storage / MediaType / Device ─────────────────────────────────────────')
w("INSERT INTO storage (name, autochanger) VALUES ('LocalStorage', 0);")
w("INSERT INTO mediatype (mediatype, readonly) VALUES ('File', 0);")
w("INSERT INTO device (name, mediatypeid, storageid) VALUES ('FileStorage', 1, 1);")
w()

# ── Pools ─────────────────────────────────────────────────────────────────────
w('-- ─── Pools ──────────────────────────────────────────────────────────────────')
w("INSERT INTO pool (name, numvols, maxvols, useonce, usecatalog, acceptanyvolume,")
w("                  volretention, voluseduration, maxvoljobs, maxvolfiles, maxvolbytes,")
w("                  autoprune, recycle, actiononpurge, pooltype, labeltype, labelformat,")
w("                  enabled, scratchpoolid, recyclepoolid, nextpoolid,")
w("                  migrationhighbytes, migrationlowbytes, migrationtime)")
w("VALUES")
w("('Daily',   5, 10, 0, 1, 0,  604800, 0, 0, 0, 0, 1, 1, 0, 'Backup', 0, 'Daily-',  1, 0, 0, 0, 0, 0, 0),")
w("('Weekly',  4, 10, 0, 1, 0, 2592000, 0, 0, 0, 0, 1, 1, 0, 'Backup', 0, 'Weekly-', 1, 0, 0, 0, 0, 0, 0);")
w()

# ── FileSets ──────────────────────────────────────────────────────────────────
w('-- ─── FileSets ───────────────────────────────────────────────────────────────')
w("INSERT INTO fileset (fileset, md5, createtime) VALUES")
w(f"('LinuxAll', 'aabbccddeeff0011', '{ts(days=180)}'),")
w(f"('MySQL',    '1122334455667788', '{ts(days=180)}'),")
w(f"('WebFiles', '99aabbccddeeffaa', '{ts(days=180)}'),")
w(f"('AppFiles', 'ffeeddccbbaa9988', '{ts(days=180)}');")
w()

# ── Media volumes ─────────────────────────────────────────────────────────────
# mediaid: 1=Daily-0001..5=Daily-0005  6=Weekly-0001..10=Weekly-0005
w('-- ─── Media volumes ──────────────────────────────────────────────────────────')
w("-- poolid: 1=Daily  2=Weekly  storageid=1  mediatypeid=1  deviceid=1")
w("INSERT INTO media (volumename, slot, poolid, mediatype, mediatypeid, labeltype,")
w("                   firstwritten, lastwritten, labeldate,")
w("                   voljobs, volfiles, volblocks, volmounts, volbytes,")
w("                   volparts, volerrors, volwrites, volcapacitybytes,")
w("                   volstatus, enabled, recycle, actiononpurge,")
w("                   volretention, voluseduration, maxvoljobs, maxvolfiles, maxvolbytes,")
w("                   inchanger, storageid, deviceid, mediaaddressing,")
w("                   volreadtime, volwritetime, endfile, endblock,")
w("                   locationid, recyclecount, scratchpoolid, recyclepoolid, comment)")
w("VALUES")
media = [
    ('Daily-0001', 1, 'Append', ts(days=6), ts(hours=6),  ts(days=6),  10, 10000, 640, 10, 64424509440),
    ('Daily-0002', 1, 'Full',   ts(days=5), ts(days=5),   ts(days=5),   6,  6000, 400,  6, 32212254720),
    ('Daily-0003', 1, 'Full',   ts(days=4), ts(days=4),   ts(days=4),   6,  6000, 400,  6, 32212254720),
    ('Daily-0004', 1, 'Purged', ts(days=3), ts(days=3),   ts(days=3),   4,  4000, 256,  4, 21474836480),
    ('Daily-0005', 1, 'Append', ts(days=2), ts(hours=1),  ts(days=2),  12, 12000, 768, 12, 85899345920),
    ('Weekly-0001', 2, 'Full',  ts(days=28), ts(days=21), ts(days=28),  4, 50000,3200,  4, 322122547200),
    ('Weekly-0002', 2, 'Full',  ts(days=21), ts(days=14), ts(days=21),  4, 50000,3200,  4, 322122547200),
    ('Weekly-0003', 2, 'Append',ts(days=14), ts(days=7),  ts(days=14),  4, 50000,3200,  4, 322122547200),
    ('Weekly-0004', 2, 'Append',ts(days=7),  ts(hours=2), ts(days=7),   4, 40000,2560,  4, 214748364800),
    ('Weekly-0005', 2, 'Recycle',ts(days=35),ts(days=35), ts(days=35),  4, 50000,3200,  4, 322122547200),
]
for i, (name, pool, status, fw, lw, ld, vj, vf, vb, vm, vbytes) in enumerate(media):
    comma = ',' if i < len(media) - 1 else ';'
    w(f"('{name}', 0, {pool}, 'File', 1, 0,")
    w(f" '{fw}', '{lw}', '{ld}',")
    w(f" {vj}, {vf}, {vb}, {vm}, {vbytes}, 0, 0, {vj}, 107374182400,")
    w(f" '{status}', 1, 1, 0, 604800, 0, 0, 0, 0, 0, 1, 1, 0, 0, 3600, 0, 0, 0, 0, 0, 0, ''){comma}")
w()

# ── Jobs (last 7 days, 28 rows) ───────────────────────────────────────────────
# clientid: 1=web 2=db 3=files 4=app
# poolid:   1=Daily 2=Weekly
# filesetid:1=LinuxAll 2=MySQL 3=WebFiles 4=AppFiles
w('-- ─── Jobs (last 7 days) ─────────────────────────────────────────────────────')
w("-- Type B=Backup  Level F=Full I=Incremental D=Differential")
w("-- Status T=OK W=Warnings E=Error R=Running")
w("INSERT INTO job (job, name, type, level, clientid, jobstatus,")
w("                 schedtime, starttime, endtime,")
w("                 jobtdate, volsessionid, volsessiontime,")
w("                 jobfiles, jobbytes, joberrors, jobmissingfiles,")
w("                 poolid, filesetid, purgedfiles, hasbase)")
w("VALUES")

# job records: (name_suffix, level, clientid, status, sched_days, sched_hours,
#               start_offset_min, end_offset_min, files, bytes, errors, poolid, filesetid, vsid, vstid)
# For running job: sched=forward=False, end_offset_min is POSITIVE (use forward flag)

jobs = [
    # web-server (clientid=1, filesetid=3)
    ('web-server.example.com', 'F', 1, 'T', 7,  0,  1, 42,   125000, 10737418240, 0, 2, 3,  1, 1000001),
    ('web-server.example.com', 'I', 1, 'T', 5,  0,  1,  8,    12000,  1073741824, 0, 1, 3,  2, 1000001),
    ('web-server.example.com', 'I', 1, 'W', 4,  0,  1,  9,    11500,   966367641, 2, 1, 3,  3, 1000001),
    ('web-server.example.com', 'I', 1, 'T', 3,  0,  1,  7,    10800,   859832319, 0, 1, 3,  4, 1000001),
    ('web-server.example.com', 'I', 1, 'T', 2,  0,  1,  6,     9500,   751619276, 0, 1, 3,  5, 1000001),
    # jobid=6: within last 24h → file records
    ('web-server.example.com', 'I', 1, 'T', 0,  6,  1,  5,     8200,   644245094, 0, 1, 3,  6, 1000001),
    # jobid=7: very recent
    ('web-server.example.com', 'I', 1, 'T', 0,  2,  1,  4,     5100,   429496729, 0, 1, 3,  7, 1000001),
    # db-server (clientid=2, filesetid=2)
    ('db-server.example.com',  'F', 2, 'T', 7,  0,  2, 95,   280000, 53687091200, 0, 2, 2,  8, 1000002),
    ('db-server.example.com',  'I', 2, 'T', 5,  0,  2, 22,    45000,  4831838208, 0, 1, 2,  9, 1000002),
    ('db-server.example.com',  'I', 2, 'E', 4,  0,  2,  5,        0,           0, 1, 1, 2, 10, 1000002),
    ('db-server.example.com',  'I', 2, 'T', 3,  0,  2, 18,    42000,  4508876800, 0, 1, 2, 11, 1000002),
    ('db-server.example.com',  'I', 2, 'T', 2,  0,  2, 20,    48000,  5154226176, 0, 1, 2, 12, 1000002),
    # jobid=13: within last 24h, has warnings
    ('db-server.example.com',  'I', 2, 'W', 0,  5,  2, 25,    51000,  5476982784, 3, 1, 2, 13, 1000002),
    # jobid=14: very recent → file records
    ('db-server.example.com',  'I', 2, 'T', 0,  3,  2, 19,    44000,  4723721216, 0, 1, 2, 14, 1000002),
    # files-server (clientid=3, filesetid=1)
    ('files-server.example.com', 'F', 3, 'T', 7, 0,  3, 210,  950000, 214748364800, 0, 2, 1, 15, 1000003),
    ('files-server.example.com', 'D', 3, 'T', 6, 0,  3,  55,   85000,  21474836480, 0, 1, 1, 16, 1000003),
    ('files-server.example.com', 'I', 3, 'T', 5, 0,  3,  28,   32000,   3221225472, 0, 1, 1, 17, 1000003),
    ('files-server.example.com', 'I', 3, 'T', 4, 0,  3,  31,   35000,   3758096384, 0, 1, 1, 18, 1000003),
    ('files-server.example.com', 'I', 3, 'E', 3, 0,  3,   8,       0,            0, 1, 1, 1, 19, 1000003),
    ('files-server.example.com', 'I', 3, 'T', 2, 0,  3,  35,   41000,   4398046511, 0, 1, 1, 20, 1000003),
    # jobid=21: within last 24h
    ('files-server.example.com', 'I', 3, 'T', 0,  8, 3,  30,   38000,   4026531840, 0, 1, 1, 21, 1000003),
    # jobid=22: running (endtime in future)
    ('files-server.example.com', 'I', 3, 'R', 0,  0, 28, 30,    5200,    537919488, 0, 1, 1, 22, 1000003),
    # app-server (clientid=4, filesetid=4)
    ('app-server.example.com',   'F', 4, 'T', 7, 0,  2,  65,   95000,  19327352832, 0, 2, 4, 23, 1000004),
    ('app-server.example.com',   'I', 4, 'T', 5, 0,  2,  12,    8500,    966367641, 0, 1, 4, 24, 1000004),
    ('app-server.example.com',   'I', 4, 'T', 4, 0,  2,  11,    8000,    912680550, 0, 1, 4, 25, 1000004),
    ('app-server.example.com',   'I', 4, 'T', 3, 0,  2,  10,    7500,    859832319, 0, 1, 4, 26, 1000004),
    # jobid=27: within last 24h
    ('app-server.example.com',   'I', 4, 'T', 0,  6, 2,   9,    7000,    805306368, 0, 1, 4, 27, 1000004),
    # jobid=28: very recent → file records
    ('app-server.example.com',   'I', 4, 'T', 0,  1, 2,   7,    6200,    644245094, 0, 1, 4, 28, 1000004),
]

# Running job is jobid=22 (files-server, status=R)
RUNNING_JOB_IDX = 21  # 0-based index of the running job

for i, job in enumerate(jobs):
    (name, level, clientid, status, sched_days, sched_hours,
     start_off, end_off, files, jobbytes, errors, poolid, filesetid, vsid, vstid) = job

    comma = ',' if i < len(jobs) - 1 else ';'
    jobid = i + 1

    if i == RUNNING_JOB_IDX:
        # Running: sched = now - 30min, start = now - 28min, end = now + 30min
        sched_ts  = ts(minutes=30)
        start_ts  = ts(minutes=28)
        end_ts    = ts(minutes=30, forward=True)
    else:
        sched_ts = ts(days=sched_days, hours=sched_hours)
        start_ts = ts(days=sched_days, hours=sched_hours, minutes=0)
        # shift start by start_off minutes forward from sched
        sched_dt = now - timedelta(days=sched_days, hours=sched_hours)
        start_dt = sched_dt + timedelta(minutes=start_off)
        end_dt   = sched_dt + timedelta(minutes=end_off)
        start_ts = start_dt.strftime('%Y-%m-%d %H:%M:%S')
        end_ts   = end_dt.strftime('%Y-%m-%d %H:%M:%S')

    # Build job name from client name + date from sched_ts
    job_name_ts = sched_ts[:10].replace('-', '-') + '.' + sched_ts[11:16].replace(':', '.')
    job_name = f'{name}.{job_name_ts}'

    w(f"-- jobid={jobid}: {name} {level}")
    w(f"('{job_name}', '{name}', 'B', '{level}', {clientid}, '{status}',")
    w(f" '{sched_ts}', '{start_ts}', '{end_ts}',")
    w(f" 0, {vsid}, {vstid}, {files}, {jobbytes}, {errors}, 0,")
    w(f" {poolid}, {filesetid}, 0, 0){comma}")
w()

# ── JobHisto (days 8-35, 4 clients × 4 entries = 16 rows) ────────────────────
w('-- ─── JobHisto (days 8-35) ──────────────────────────────────────────────────')
w("INSERT INTO jobhisto (jobid, job, name, type, level, clientid, jobstatus,")
w("                      schedtime, starttime, endtime,")
w("                      jobtdate, volsessionid, volsessiontime,")
w("                      jobfiles, jobbytes, joberrors, jobmissingfiles,")
w("                      poolid, filesetid, purgedfiles, hasbase)")
w("VALUES")

histo = [
    # web-server (clientid=1, filesetid=3)
    (1001, 'web-server.example.com',   'F', 1, 'T', 35, 0,  1, 45,  120000, 10200547328, 0, 2, 3, 101, 2000001),
    (1002, 'web-server.example.com',   'I', 1, 'T', 28, 0,  1,  7,   11000,   966367641, 0, 1, 3, 102, 2000001),
    (1003, 'web-server.example.com',   'I', 1, 'W', 21, 0,  1,  8,   10500,   912680550, 1, 1, 3, 103, 2000001),
    (1004, 'web-server.example.com',   'I', 1, 'T', 14, 0,  1,  6,    9800,   805306368, 0, 1, 3, 104, 2000001),
    # db-server (clientid=2, filesetid=2)
    (1005, 'db-server.example.com',    'F', 2, 'T', 35, 0,  3,100,  270000, 53687091200, 0, 2, 2, 105, 2000002),
    (1006, 'db-server.example.com',    'I', 2, 'T', 28, 0,  2, 20,   43000,  4617089843, 0, 1, 2, 106, 2000002),
    (1007, 'db-server.example.com',    'I', 2, 'E', 21, 0,  2,  4,       0,           0, 1, 1, 2, 107, 2000002),
    (1008, 'db-server.example.com',    'I', 2, 'T', 14, 0,  2, 22,   47000,  5046586572, 0, 1, 2, 108, 2000002),
    # files-server (clientid=3, filesetid=1)
    (1009, 'files-server.example.com', 'F', 3, 'T', 35, 0,  5,225,  920000,204010946560, 0, 2, 1, 109, 2000003),
    (1010, 'files-server.example.com', 'D', 3, 'T', 28, 0,  4, 60,   80000, 20132659200, 0, 1, 1, 110, 2000003),
    (1011, 'files-server.example.com', 'I', 3, 'T', 21, 0,  4, 30,   30000,  3006477107, 0, 1, 1, 111, 2000003),
    (1012, 'files-server.example.com', 'I', 3, 'T', 14, 0,  4, 28,   28000,  2952790016, 0, 1, 1, 112, 2000003),
    # app-server (clientid=4, filesetid=4)
    (1013, 'app-server.example.com',   'F', 4, 'T', 35, 0,  2, 60,   90000, 18253611008, 0, 2, 4, 113, 2000004),
    (1014, 'app-server.example.com',   'I', 4, 'T', 28, 0,  2, 10,    8000,   805306368, 0, 1, 4, 114, 2000004),
    (1015, 'app-server.example.com',   'I', 4, 'T', 21, 0,  2,  9,    7500,   751619276, 0, 1, 4, 115, 2000004),
    (1016, 'app-server.example.com',   'I', 4, 'T', 14, 0,  2,  8,    7000,   698351450, 0, 1, 4, 116, 2000004),
]

for i, h in enumerate(histo):
    (hjobid, name, level, clientid, status,
     sched_days, sched_hours, start_off, end_off,
     files, jobbytes, errors, poolid, filesetid, vsid, vstid) = h
    comma = ',' if i < len(histo) - 1 else ';'

    sched_dt = now - timedelta(days=sched_days, hours=sched_hours)
    start_dt = sched_dt + timedelta(minutes=start_off)
    end_dt   = sched_dt + timedelta(minutes=end_off)
    sched_ts = sched_dt.strftime('%Y-%m-%d %H:%M:%S')
    start_ts = start_dt.strftime('%Y-%m-%d %H:%M:%S')
    end_ts   = end_dt.strftime('%Y-%m-%d %H:%M:%S')
    job_name_ts = sched_ts[:10] + '.' + sched_ts[11:16].replace(':', '.')
    job_name = f'{name}.h{i+1:02d}'

    w(f"({hjobid}, '{job_name}', '{name}', 'B', '{level}', {clientid}, '{status}',")
    w(f" '{sched_ts}', '{start_ts}', '{end_ts}',")
    w(f" 0, {vsid}, {vstid}, {files}, {jobbytes}, {errors}, 0,")
    w(f" {poolid}, {filesetid}, 0, 0){comma}")
w()

# ── Paths (16 entries, depth 1-4 levels for jsTree testing) ──────────────────
w('-- ─── Paths (depth 1-4 for jsTree) ─────────────────────────────────────────')
w("-- pathid: 1=/var/log/  2=/var/log/nginx/  3=/etc/  4=/etc/nginx/")
w("--         5=/var/lib/mysql/  6=/var/lib/mysql/data/  7=/var/lib/mysql/binlog/")
w("--         8=/home/deploy/  9=/srv/data/  10=/srv/data/uploads/")
w("--         11=/srv/data/backups/  12=/var/www/html/  13=/var/www/html/static/")
w("--         14=/opt/app/  15=/opt/app/releases/  16=/backup/")
w("INSERT INTO path (path) VALUES")
paths = [
    '/var/log/',
    '/var/log/nginx/',
    '/etc/',
    '/etc/nginx/',
    '/var/lib/mysql/',
    '/var/lib/mysql/data/',
    '/var/lib/mysql/binlog/',
    '/home/deploy/',
    '/srv/data/',
    '/srv/data/uploads/',
    '/srv/data/backups/',
    '/var/www/html/',
    '/var/www/html/static/',
    '/opt/app/',
    '/opt/app/releases/',
    '/backup/',
]
for i, p in enumerate(paths):
    comma = ',' if i < len(paths) - 1 else ';'
    w(f"('{p}'){comma}")
w()

# ── FileNames ─────────────────────────────────────────────────────────────────
w('-- ─── FileNames ─────────────────────────────────────────────────────────────')
w("-- filenameid: 1=access.log  2=error.log  3=syslog  4=assets.tar.gz")
w("--             5=ibdata1  6=ib_logfile0  7=ib_logfile1  8=mysql-bin.000001")
w("--             9=database-dump.sql.gz  10=uploads.tar.gz  11=media-archive.tar.gz")
w("--             12=backup-full.tar.gz  13=deploy.tar.gz  14=release.tar.gz  15=app.log")
w("INSERT INTO filename (name) VALUES")
filenames = [
    'access.log',
    'error.log',
    'syslog',
    'assets.tar.gz',
    'ibdata1',
    'ib_logfile0',
    'ib_logfile1',
    'mysql-bin.000001',
    'database-dump.sql.gz',
    'uploads.tar.gz',
    'media-archive.tar.gz',
    'backup-full.tar.gz',
    'deploy.tar.gz',
    'release.tar.gz',
    'app.log',
]
for i, fn in enumerate(filenames):
    comma = ',' if i < len(filenames) - 1 else ';'
    w(f"('{fn}'){comma}")
w()

# ── File records for jobs within last 24h ─────────────────────────────────────
# Bacula lstat size field (position 7, 0-indexed):
#   EAAA  =  1 MiB   (1 048 576)  — below big_files threshold
#   sAAA  = 11 MiB   (11 534 336)
#   8AAA  = 15 MiB   (15 728 640)
#   DIAAA = 50 MiB   (52 428 800)
#   GQAAA = 100 MiB  (104 857 600)
#   MgAAA = 200 MiB  (209 715 200)
#   gAAAA = 512 MiB  (536 870 912)
w('-- ─── File records (jobs within last 24h → big_files jsTree) ────────────────')
w("-- lstat position 7 = file size in Bacula base64")

def file_insert(jobid, records):
    w(f"-- jobid={jobid}")
    w(f"INSERT INTO file (fileindex, jobid, pathid, filenameid, markid, lstat, md5) VALUES")
    for i, (fileindex, pathid, filenameid, size_enc) in enumerate(records):
        comma = ',' if i < len(records) - 1 else ';'
        w(f"({fileindex}, {jobid}, {pathid}, {filenameid}, 0, "
          f"'bN Gj{fileindex} IiIf B A A A {size_enc} KA IA BqBmIA BqBmIA BqBmIA A', '0'){comma}")
    w()


# jobid=6: web-server, 20h ago
# /var/log/nginx/access.log (50M), /var/log/nginx/error.log (15M),
# /var/log/syslog (11M), /var/www/html/static/assets.tar.gz (100M)
file_insert(6, [
    (1, 2,  1, 'DIAAA'),   # /var/log/nginx/access.log        50M  pathid=2, filenameid=1
    (2, 2,  2, '8AAA'),    # /var/log/nginx/error.log         15M  pathid=2, filenameid=2
    (3, 1,  3, 'sAAA'),    # /var/log/syslog                  11M  pathid=1, filenameid=3
    (4, 13, 4, 'GQAAA'),   # /var/www/html/static/assets.tar.gz 100M pathid=13, filenameid=4
])

# jobid=14: db-server, 3h ago
# /var/lib/mysql/ibdata1 (512M), /var/lib/mysql/data/ib_logfile0 (100M),
# /var/lib/mysql/data/ib_logfile1 (100M), /var/lib/mysql/binlog/mysql-bin.000001 (50M),
# /backup/database-dump.sql.gz (200M)
file_insert(14, [
    (1, 5,  5, 'gAAAA'),   # /var/lib/mysql/ibdata1            512M pathid=5, filenameid=5
    (2, 6,  6, 'GQAAA'),   # /var/lib/mysql/data/ib_logfile0   100M pathid=6, filenameid=6
    (3, 6,  7, 'GQAAA'),   # /var/lib/mysql/data/ib_logfile1   100M pathid=6, filenameid=7
    (4, 7,  8, 'DIAAA'),   # /var/lib/mysql/binlog/mysql-bin   50M  pathid=7, filenameid=8
    (5, 16, 9, 'MgAAA'),   # /backup/database-dump.sql.gz      200M pathid=16, filenameid=9
])

# jobid=22: files-server, running (within 24h)
# /srv/data/uploads/uploads.tar.gz (512M), /srv/data/uploads/media-archive.tar.gz (200M),
# /srv/data/backups/backup-full.tar.gz (100M), /home/deploy/deploy.tar.gz (50M)
file_insert(22, [
    (1, 10, 10, 'gAAAA'),  # /srv/data/uploads/uploads.tar.gz  512M pathid=10, filenameid=10
    (2, 10, 11, 'MgAAA'),  # /srv/data/uploads/media-archive   200M pathid=10, filenameid=11
    (3, 11, 12, 'GQAAA'),  # /srv/data/backups/backup-full     100M pathid=11, filenameid=12
    (4, 8,  13, 'DIAAA'),  # /home/deploy/deploy.tar.gz        50M  pathid=8,  filenameid=13
])

# jobid=28: app-server, 1h ago
# /opt/app/releases/release.tar.gz (200M), /opt/app/app.log (15M), /var/log/app.log (11M)
file_insert(28, [
    (1, 15, 14, 'MgAAA'),  # /opt/app/releases/release.tar.gz 200M pathid=15, filenameid=14
    (2, 14, 15, '8AAA'),   # /opt/app/app.log                  15M  pathid=14, filenameid=15
    (3, 1,  15, 'sAAA'),   # /var/log/app.log                  11M  pathid=1,  filenameid=15
])

# ── JobMedia ──────────────────────────────────────────────────────────────────
w('-- ─── JobMedia (link jobs to volumes) ──────────────────────────────────────')
w("-- mediaid: 1-5=Daily-0001..0005  6-10=Weekly-0001..0005")
w("INSERT INTO jobmedia (jobmediaid, jobid, mediaid, firstindex, lastindex,")
w("                      startfile, endfile, startblock, endblock, volindex)")
w("VALUES")
jobmedia = [
    # Web-server jobs
    ( 1,  1,  6,       1, 125000,  0, 0,        0,  4194304, 1),  # Full on Weekly-0001
    ( 2,  2,  1,       1,  12000,  0, 0,        0,   409600, 1),
    ( 3,  3,  1,   12001,  23500,  0, 0,   409601,   802816, 1),
    ( 4,  4,  1,   23501,  34300,  0, 0,   802817,  1171456, 1),
    ( 5,  5,  5,   34301,  43800,  0, 0,  1171457,  1499136, 1),
    ( 6,  6,  5,   43801,  52000,  0, 0,  1499137,  1777664, 1),
    ( 7,  7,  5,   52001,  57100,  0, 0,  1777665,  1941504, 1),
    # db-server jobs
    ( 8,  8,  7,       1, 280000,  0, 0,        0,  9175040, 1),  # Full on Weekly-0002
    ( 9,  9,  5,   57101, 102100,  0, 0,  1941505,  3342336, 1),
    (10, 10,  5,  102101, 102101,  0, 0,  3342337,  3342337, 1),
    (11, 11,  5,  102102, 144100,  0, 0,  3342338,  4718592, 1),
    (12, 12,  2,  144101, 192100,  0, 0,  4718593,  6291456, 1),
    (13, 13,  2,  192101, 243100,  0, 0,  6291457,  7962624, 1),
    (14, 14,  5,  243101, 287100,  0, 0,  7962625,  9404416, 1),
    # files-server jobs
    (15, 15,  8,       1, 950000,  0, 0,        0, 31457280, 1),  # Full on Weekly-0003
    (16, 16,  5,  287101, 372100,  0, 0,  9404417, 12189696, 1),
    (17, 17,  5,  372101, 404100,  0, 0, 12189697, 13238272, 1),
    (18, 18,  3,  404101, 439100,  0, 0, 13238273, 14385152, 1),
    (19, 19,  3,  439101, 439101,  0, 0, 14385153, 14385153, 1),
    (20, 20,  3,  439102, 480100,  0, 0, 14385154, 15728640, 1),
    (21, 21,  3,  480101, 518100,  0, 0, 15728641, 16973824, 1),
    (22, 22,  5,  518101, 523300,  0, 0, 16973825, 17145856, 1),  # running
    # app-server jobs
    (23, 23,  9,       1,  95000,  0, 0,        0,  3112960, 1),  # Full on Weekly-0004
    (24, 24,  1,  523301, 531800,  0, 0, 17145857, 17424384, 1),
    (25, 25,  1,  531801, 539800,  0, 0, 17424385, 17686528, 1),
    (26, 26,  4,  539801, 547300,  0, 0, 17686529, 17932288, 1),
    (27, 27,  4,  547301, 554300,  0, 0, 17932289, 18161664, 1),
    (28, 28,  5,  554301, 560500,  0, 0, 18161665, 18366464, 1),
]
for i, jm in enumerate(jobmedia):
    comma = ',' if i < len(jobmedia) - 1 else ';'
    (jmid, jobid, mediaid, fi, li, sf, ef, sb, eb, vi) = jm
    w(f"({jmid}, {jobid}, {mediaid}, {fi}, {li}, {sf}, {ef}, {sb}, {eb}, {vi}){comma}")
w()

# ── Logs for warning/error jobs ───────────────────────────────────────────────
w('-- ─── Logs for warning/error jobs ──────────────────────────────────────────')
w("INSERT INTO log (jobid, time, logtext) VALUES")
logs = [
    (3,  ts(days=4, minutes=0),
     'web-server.example.com-fd JobId 3: Warning: /var/log/syslog: file size shrunk by 1024 bytes; not saved.'),
    (13, ts(hours=5, minutes=0),
     'db-server.example.com-fd JobId 13: Warning: /var/lib/mysql/mysql-bin.000001: file changed.'),
    (13, ts(hours=5, minutes=0),
     'db-server.example.com-fd JobId 13: Warning: /var/lib/mysql/mysql-bin.000002: file changed.'),
    (13, ts(hours=5, minutes=0),
     'db-server.example.com-dir JobId 13: Warning: 3 files not saved due to file permission error.'),
    (1003, ts(days=21, minutes=0),
     'web-server.example.com-fd JobId 1003: Warning: /var/log/auth.log: file size shrunk.'),
    (1007, ts(days=21, minutes=0),
     'db-server.example.com-fd JobId 1007: Error: /var/lib/mysql/ibdata1: could not read.'),
]
for i, (jobid, log_ts, logtext) in enumerate(logs):
    comma = ',' if i < len(logs) - 1 else ';'
    w(f"({jobid}, '{log_ts}', '{logtext}'){comma}")
w()

# ── Write output ──────────────────────────────────────────────────────────────
out = '\n'.join(lines) + '\n'
if '--stdout' in sys.argv:
    sys.stdout.write(out)
else:
    out_path = os.path.normpath(OUT)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, 'w') as f:
        f.write(out)
    print(f"Written {len(lines)} lines to {out_path}")
