-- Bacula test seed data
-- Generated by scripts/generate_seed.py — do NOT edit by hand
-- Generated at: 2026-06-01 07:41:00 UTC

-- ─── Status codes ──────────────────────────────────────────────────────────
INSERT INTO status (jobstatus, jobstatuslong, severity) VALUES
('C', 'Created but not yet running', 15),
('R', 'Running', 15),
('B', 'Blocked', 15),
('T', 'Terminated normally', 10),
('W', 'Terminated normally with warnings', 20),
('E', 'Terminated in Error', 25),
('e', 'Non-fatal error', 20),
('f', 'Fatal error', 100),
('D', 'Verify Differences', 15),
('A', 'Canceled by the user', 15),
('I', 'Incomplete Job', 15),
('F', 'Waiting on the File daemon', 15),
('S', 'Waiting on the Storage daemon', 15),
('m', 'Waiting for a new Volume to be mounted', 15),
('M', 'Waiting for a Mount', 15),
('s', 'Waiting for Storage resource', 15),
('j', 'Waiting for Job resource', 15),
('c', 'Waiting for Client resource', 15),
('d', 'Waiting for Maximum jobs', 15),
('t', 'Waiting for Start Time', 15),
('p', 'Waiting for higher priority job', 15),
('i', 'Doing batch insert file records', 15),
('a', 'SD despooling attributes', 15),
('l', 'Doing data despooling', 15),
('L', 'Committing data (last despool)', 15);

-- ─── Clients ───────────────────────────────────────────────────────────────
INSERT INTO client (name, uname, autoprune, fileretention, jobretention) VALUES
('web-server.example.com', 'web-server.example.com-fd Linux x86_64 9.4.2 (01Jan22)', 1, 1209600, 2592000),
('db-server.example.com', 'db-server.example.com-fd Linux x86_64 9.4.2 (01Jan22)', 1, 1209600, 2592000),
('files-server.example.com', 'files-server.example.com-fd Linux x86_64 9.4.2 (01Jan22)', 1, 1209600, 2592000),
('app-server.example.com', 'app-server.example.com-fd Linux x86_64 9.4.2 (01Jan22)', 1, 1209600, 2592000);

-- ─── Storage / MediaType / Device ─────────────────────────────────────────
INSERT INTO storage (name, autochanger) VALUES ('LocalStorage', 0);
INSERT INTO mediatype (mediatype, readonly) VALUES ('File', 0);
INSERT INTO device (name, mediatypeid, storageid) VALUES ('FileStorage', 1, 1);

-- ─── Pools ──────────────────────────────────────────────────────────────────
INSERT INTO pool (name, numvols, maxvols, useonce, usecatalog, acceptanyvolume,
                  volretention, voluseduration, maxvoljobs, maxvolfiles, maxvolbytes,
                  autoprune, recycle, actiononpurge, pooltype, labeltype, labelformat,
                  enabled, scratchpoolid, recyclepoolid, nextpoolid,
                  migrationhighbytes, migrationlowbytes, migrationtime)
VALUES
('Daily',   5, 10, 0, 1, 0,  604800, 0, 0, 0, 0, 1, 1, 0, 'Backup', 0, 'Daily-',  1, 0, 0, 0, 0, 0, 0),
('Weekly',  4, 10, 0, 1, 0, 2592000, 0, 0, 0, 0, 1, 1, 0, 'Backup', 0, 'Weekly-', 1, 0, 0, 0, 0, 0, 0);

-- ─── FileSets ───────────────────────────────────────────────────────────────
INSERT INTO fileset (fileset, md5, createtime) VALUES
('LinuxAll', 'aabbccddeeff0011', '2025-12-03 07:41:00'),
('MySQL',    '1122334455667788', '2025-12-03 07:41:00'),
('WebFiles', '99aabbccddeeffaa', '2025-12-03 07:41:00'),
('AppFiles', 'ffeeddccbbaa9988', '2025-12-03 07:41:00');

-- ─── Media volumes ──────────────────────────────────────────────────────────
-- poolid: 1=Daily  2=Weekly  storageid=1  mediatypeid=1  deviceid=1
INSERT INTO media (volumename, slot, poolid, mediatype, mediatypeid, labeltype,
                   firstwritten, lastwritten, labeldate,
                   voljobs, volfiles, volblocks, volmounts, volbytes,
                   volparts, volerrors, volwrites, volcapacitybytes,
                   volstatus, enabled, recycle, actiononpurge,
                   volretention, voluseduration, maxvoljobs, maxvolfiles, maxvolbytes,
                   inchanger, storageid, deviceid, mediaaddressing,
                   volreadtime, volwritetime, endfile, endblock,
                   locationid, recyclecount, scratchpoolid, recyclepoolid, comment)
VALUES
('Daily-0001', 0, 1, 'File', 1, 0,
 '2026-05-26 07:41:00', '2026-06-01 01:41:00', '2026-05-26 07:41:00',
 10, 10000, 640, 10, 64424509440, 0, 0, 10, 107374182400,
 'Append', 1, 1, 0, 604800, 0, 0, 0, 0, 0, 1, 1, 0, 0, 3600, 0, 0, 0, 0, 0, 0, ''),
('Daily-0002', 0, 1, 'File', 1, 0,
 '2026-05-27 07:41:00', '2026-05-27 07:41:00', '2026-05-27 07:41:00',
 6, 6000, 400, 6, 32212254720, 0, 0, 6, 107374182400,
 'Full', 1, 1, 0, 604800, 0, 0, 0, 0, 0, 1, 1, 0, 0, 3600, 0, 0, 0, 0, 0, 0, ''),
('Daily-0003', 0, 1, 'File', 1, 0,
 '2026-05-28 07:41:00', '2026-05-28 07:41:00', '2026-05-28 07:41:00',
 6, 6000, 400, 6, 32212254720, 0, 0, 6, 107374182400,
 'Full', 1, 1, 0, 604800, 0, 0, 0, 0, 0, 1, 1, 0, 0, 3600, 0, 0, 0, 0, 0, 0, ''),
('Daily-0004', 0, 1, 'File', 1, 0,
 '2026-05-29 07:41:00', '2026-05-29 07:41:00', '2026-05-29 07:41:00',
 4, 4000, 256, 4, 21474836480, 0, 0, 4, 107374182400,
 'Purged', 1, 1, 0, 604800, 0, 0, 0, 0, 0, 1, 1, 0, 0, 3600, 0, 0, 0, 0, 0, 0, ''),
('Daily-0005', 0, 1, 'File', 1, 0,
 '2026-05-30 07:41:00', '2026-06-01 06:41:00', '2026-05-30 07:41:00',
 12, 12000, 768, 12, 85899345920, 0, 0, 12, 107374182400,
 'Append', 1, 1, 0, 604800, 0, 0, 0, 0, 0, 1, 1, 0, 0, 3600, 0, 0, 0, 0, 0, 0, ''),
('Weekly-0001', 0, 2, 'File', 1, 0,
 '2026-05-04 07:41:00', '2026-05-11 07:41:00', '2026-05-04 07:41:00',
 4, 50000, 3200, 4, 322122547200, 0, 0, 4, 107374182400,
 'Full', 1, 1, 0, 604800, 0, 0, 0, 0, 0, 1, 1, 0, 0, 3600, 0, 0, 0, 0, 0, 0, ''),
('Weekly-0002', 0, 2, 'File', 1, 0,
 '2026-05-11 07:41:00', '2026-05-18 07:41:00', '2026-05-11 07:41:00',
 4, 50000, 3200, 4, 322122547200, 0, 0, 4, 107374182400,
 'Full', 1, 1, 0, 604800, 0, 0, 0, 0, 0, 1, 1, 0, 0, 3600, 0, 0, 0, 0, 0, 0, ''),
('Weekly-0003', 0, 2, 'File', 1, 0,
 '2026-05-18 07:41:00', '2026-05-25 07:41:00', '2026-05-18 07:41:00',
 4, 50000, 3200, 4, 322122547200, 0, 0, 4, 107374182400,
 'Append', 1, 1, 0, 604800, 0, 0, 0, 0, 0, 1, 1, 0, 0, 3600, 0, 0, 0, 0, 0, 0, ''),
('Weekly-0004', 0, 2, 'File', 1, 0,
 '2026-05-25 07:41:00', '2026-06-01 05:41:00', '2026-05-25 07:41:00',
 4, 40000, 2560, 4, 214748364800, 0, 0, 4, 107374182400,
 'Append', 1, 1, 0, 604800, 0, 0, 0, 0, 0, 1, 1, 0, 0, 3600, 0, 0, 0, 0, 0, 0, ''),
('Weekly-0005', 0, 2, 'File', 1, 0,
 '2026-04-27 07:41:00', '2026-04-27 07:41:00', '2026-04-27 07:41:00',
 4, 50000, 3200, 4, 322122547200, 0, 0, 4, 107374182400,
 'Recycle', 1, 1, 0, 604800, 0, 0, 0, 0, 0, 1, 1, 0, 0, 3600, 0, 0, 0, 0, 0, 0, '');

-- ─── Jobs (last 7 days) ─────────────────────────────────────────────────────
-- Type B=Backup  Level F=Full I=Incremental D=Differential
-- Status T=OK W=Warnings E=Error R=Running
INSERT INTO job (job, name, type, level, clientid, jobstatus,
                 schedtime, starttime, endtime,
                 jobtdate, volsessionid, volsessiontime,
                 jobfiles, jobbytes, joberrors, jobmissingfiles,
                 poolid, filesetid, purgedfiles, hasbase)
VALUES
-- jobid=1: web-server.example.com F
('web-server.example.com.2026-05-25.07.41', 'web-server.example.com', 'B', 'F', 1, 'T',
 '2026-05-25 07:41:00', '2026-05-25 07:42:00', '2026-05-25 08:23:00',
 0, 1, 1000001, 125000, 10737418240, 0, 0,
 2, 3, 0, 0),
-- jobid=2: web-server.example.com I
('web-server.example.com.2026-05-27.07.41', 'web-server.example.com', 'B', 'I', 1, 'T',
 '2026-05-27 07:41:00', '2026-05-27 07:42:00', '2026-05-27 07:49:00',
 0, 2, 1000001, 12000, 1073741824, 0, 0,
 1, 3, 0, 0),
-- jobid=3: web-server.example.com I
('web-server.example.com.2026-05-28.07.41', 'web-server.example.com', 'B', 'I', 1, 'W',
 '2026-05-28 07:41:00', '2026-05-28 07:42:00', '2026-05-28 07:50:00',
 0, 3, 1000001, 11500, 966367641, 2, 0,
 1, 3, 0, 0),
-- jobid=4: web-server.example.com I
('web-server.example.com.2026-05-29.07.41', 'web-server.example.com', 'B', 'I', 1, 'T',
 '2026-05-29 07:41:00', '2026-05-29 07:42:00', '2026-05-29 07:48:00',
 0, 4, 1000001, 10800, 859832319, 0, 0,
 1, 3, 0, 0),
-- jobid=5: web-server.example.com I
('web-server.example.com.2026-05-30.07.41', 'web-server.example.com', 'B', 'I', 1, 'T',
 '2026-05-30 07:41:00', '2026-05-30 07:42:00', '2026-05-30 07:47:00',
 0, 5, 1000001, 9500, 751619276, 0, 0,
 1, 3, 0, 0),
-- jobid=6: web-server.example.com I
('web-server.example.com.2026-06-01.01.41', 'web-server.example.com', 'B', 'I', 1, 'T',
 '2026-06-01 01:41:00', '2026-06-01 01:42:00', '2026-06-01 01:46:00',
 0, 6, 1000001, 8200, 644245094, 0, 0,
 1, 3, 0, 0),
-- jobid=7: web-server.example.com I
('web-server.example.com.2026-06-01.05.41', 'web-server.example.com', 'B', 'I', 1, 'T',
 '2026-06-01 05:41:00', '2026-06-01 05:42:00', '2026-06-01 05:45:00',
 0, 7, 1000001, 5100, 429496729, 0, 0,
 1, 3, 0, 0),
-- jobid=8: db-server.example.com F
('db-server.example.com.2026-05-25.07.41', 'db-server.example.com', 'B', 'F', 2, 'T',
 '2026-05-25 07:41:00', '2026-05-25 07:43:00', '2026-05-25 09:16:00',
 0, 8, 1000002, 280000, 53687091200, 0, 0,
 2, 2, 0, 0),
-- jobid=9: db-server.example.com I
('db-server.example.com.2026-05-27.07.41', 'db-server.example.com', 'B', 'I', 2, 'T',
 '2026-05-27 07:41:00', '2026-05-27 07:43:00', '2026-05-27 08:03:00',
 0, 9, 1000002, 45000, 4831838208, 0, 0,
 1, 2, 0, 0),
-- jobid=10: db-server.example.com I
('db-server.example.com.2026-05-28.07.41', 'db-server.example.com', 'B', 'I', 2, 'E',
 '2026-05-28 07:41:00', '2026-05-28 07:43:00', '2026-05-28 07:46:00',
 0, 10, 1000002, 0, 0, 1, 0,
 1, 2, 0, 0),
-- jobid=11: db-server.example.com I
('db-server.example.com.2026-05-29.07.41', 'db-server.example.com', 'B', 'I', 2, 'T',
 '2026-05-29 07:41:00', '2026-05-29 07:43:00', '2026-05-29 07:59:00',
 0, 11, 1000002, 42000, 4508876800, 0, 0,
 1, 2, 0, 0),
-- jobid=12: db-server.example.com I
('db-server.example.com.2026-05-30.07.41', 'db-server.example.com', 'B', 'I', 2, 'T',
 '2026-05-30 07:41:00', '2026-05-30 07:43:00', '2026-05-30 08:01:00',
 0, 12, 1000002, 48000, 5154226176, 0, 0,
 1, 2, 0, 0),
-- jobid=13: db-server.example.com I
('db-server.example.com.2026-06-01.02.41', 'db-server.example.com', 'B', 'I', 2, 'W',
 '2026-06-01 02:41:00', '2026-06-01 02:43:00', '2026-06-01 03:06:00',
 0, 13, 1000002, 51000, 5476982784, 3, 0,
 1, 2, 0, 0),
-- jobid=14: db-server.example.com I
('db-server.example.com.2026-06-01.04.41', 'db-server.example.com', 'B', 'I', 2, 'T',
 '2026-06-01 04:41:00', '2026-06-01 04:43:00', '2026-06-01 05:00:00',
 0, 14, 1000002, 44000, 4723721216, 0, 0,
 1, 2, 0, 0),
-- jobid=15: files-server.example.com F
('files-server.example.com.2026-05-25.07.41', 'files-server.example.com', 'B', 'F', 3, 'T',
 '2026-05-25 07:41:00', '2026-05-25 07:44:00', '2026-05-25 11:11:00',
 0, 15, 1000003, 950000, 214748364800, 0, 0,
 2, 1, 0, 0),
-- jobid=16: files-server.example.com D
('files-server.example.com.2026-05-26.07.41', 'files-server.example.com', 'B', 'D', 3, 'T',
 '2026-05-26 07:41:00', '2026-05-26 07:44:00', '2026-05-26 08:36:00',
 0, 16, 1000003, 85000, 21474836480, 0, 0,
 1, 1, 0, 0),
-- jobid=17: files-server.example.com I
('files-server.example.com.2026-05-27.07.41', 'files-server.example.com', 'B', 'I', 3, 'T',
 '2026-05-27 07:41:00', '2026-05-27 07:44:00', '2026-05-27 08:09:00',
 0, 17, 1000003, 32000, 3221225472, 0, 0,
 1, 1, 0, 0),
-- jobid=18: files-server.example.com I
('files-server.example.com.2026-05-28.07.41', 'files-server.example.com', 'B', 'I', 3, 'T',
 '2026-05-28 07:41:00', '2026-05-28 07:44:00', '2026-05-28 08:12:00',
 0, 18, 1000003, 35000, 3758096384, 0, 0,
 1, 1, 0, 0),
-- jobid=19: files-server.example.com I
('files-server.example.com.2026-05-29.07.41', 'files-server.example.com', 'B', 'I', 3, 'E',
 '2026-05-29 07:41:00', '2026-05-29 07:44:00', '2026-05-29 07:49:00',
 0, 19, 1000003, 0, 0, 1, 0,
 1, 1, 0, 0),
-- jobid=20: files-server.example.com I
('files-server.example.com.2026-05-30.07.41', 'files-server.example.com', 'B', 'I', 3, 'T',
 '2026-05-30 07:41:00', '2026-05-30 07:44:00', '2026-05-30 08:16:00',
 0, 20, 1000003, 41000, 4398046511, 0, 0,
 1, 1, 0, 0),
-- jobid=21: files-server.example.com I
('files-server.example.com.2026-05-31.23.41', 'files-server.example.com', 'B', 'I', 3, 'T',
 '2026-05-31 23:41:00', '2026-05-31 23:44:00', '2026-06-01 00:11:00',
 0, 21, 1000003, 38000, 4026531840, 0, 0,
 1, 1, 0, 0),
-- jobid=22: files-server.example.com I
('files-server.example.com.2026-06-01.07.11', 'files-server.example.com', 'B', 'I', 3, 'R',
 '2026-06-01 07:11:00', '2026-06-01 07:13:00', '2026-06-01 08:11:00',
 0, 22, 1000003, 5200, 537919488, 0, 0,
 1, 1, 0, 0),
-- jobid=23: app-server.example.com F
('app-server.example.com.2026-05-25.07.41', 'app-server.example.com', 'B', 'F', 4, 'T',
 '2026-05-25 07:41:00', '2026-05-25 07:43:00', '2026-05-25 08:46:00',
 0, 23, 1000004, 95000, 19327352832, 0, 0,
 2, 4, 0, 0),
-- jobid=24: app-server.example.com I
('app-server.example.com.2026-05-27.07.41', 'app-server.example.com', 'B', 'I', 4, 'T',
 '2026-05-27 07:41:00', '2026-05-27 07:43:00', '2026-05-27 07:53:00',
 0, 24, 1000004, 8500, 966367641, 0, 0,
 1, 4, 0, 0),
-- jobid=25: app-server.example.com I
('app-server.example.com.2026-05-28.07.41', 'app-server.example.com', 'B', 'I', 4, 'T',
 '2026-05-28 07:41:00', '2026-05-28 07:43:00', '2026-05-28 07:52:00',
 0, 25, 1000004, 8000, 912680550, 0, 0,
 1, 4, 0, 0),
-- jobid=26: app-server.example.com I
('app-server.example.com.2026-05-29.07.41', 'app-server.example.com', 'B', 'I', 4, 'T',
 '2026-05-29 07:41:00', '2026-05-29 07:43:00', '2026-05-29 07:51:00',
 0, 26, 1000004, 7500, 859832319, 0, 0,
 1, 4, 0, 0),
-- jobid=27: app-server.example.com I
('app-server.example.com.2026-06-01.01.41', 'app-server.example.com', 'B', 'I', 4, 'T',
 '2026-06-01 01:41:00', '2026-06-01 01:43:00', '2026-06-01 01:50:00',
 0, 27, 1000004, 7000, 805306368, 0, 0,
 1, 4, 0, 0),
-- jobid=28: app-server.example.com I
('app-server.example.com.2026-06-01.06.41', 'app-server.example.com', 'B', 'I', 4, 'T',
 '2026-06-01 06:41:00', '2026-06-01 06:43:00', '2026-06-01 06:48:00',
 0, 28, 1000004, 6200, 644245094, 0, 0,
 1, 4, 0, 0);

-- ─── JobHisto (days 8-35) ──────────────────────────────────────────────────
INSERT INTO jobhisto (jobid, job, name, type, level, clientid, jobstatus,
                      schedtime, starttime, endtime,
                      jobtdate, volsessionid, volsessiontime,
                      jobfiles, jobbytes, joberrors, jobmissingfiles,
                      poolid, filesetid, purgedfiles, hasbase)
VALUES
(1001, 'web-server.example.com.h01', 'web-server.example.com', 'B', 'F', 1, 'T',
 '2026-04-27 07:41:00', '2026-04-27 07:42:00', '2026-04-27 08:26:00',
 0, 101, 2000001, 120000, 10200547328, 0, 0,
 2, 3, 0, 0),
(1002, 'web-server.example.com.h02', 'web-server.example.com', 'B', 'I', 1, 'T',
 '2026-05-04 07:41:00', '2026-05-04 07:42:00', '2026-05-04 07:48:00',
 0, 102, 2000001, 11000, 966367641, 0, 0,
 1, 3, 0, 0),
(1003, 'web-server.example.com.h03', 'web-server.example.com', 'B', 'I', 1, 'W',
 '2026-05-11 07:41:00', '2026-05-11 07:42:00', '2026-05-11 07:49:00',
 0, 103, 2000001, 10500, 912680550, 1, 0,
 1, 3, 0, 0),
(1004, 'web-server.example.com.h04', 'web-server.example.com', 'B', 'I', 1, 'T',
 '2026-05-18 07:41:00', '2026-05-18 07:42:00', '2026-05-18 07:47:00',
 0, 104, 2000001, 9800, 805306368, 0, 0,
 1, 3, 0, 0),
(1005, 'db-server.example.com.h05', 'db-server.example.com', 'B', 'F', 2, 'T',
 '2026-04-27 07:41:00', '2026-04-27 07:44:00', '2026-04-27 09:21:00',
 0, 105, 2000002, 270000, 53687091200, 0, 0,
 2, 2, 0, 0),
(1006, 'db-server.example.com.h06', 'db-server.example.com', 'B', 'I', 2, 'T',
 '2026-05-04 07:41:00', '2026-05-04 07:43:00', '2026-05-04 08:01:00',
 0, 106, 2000002, 43000, 4617089843, 0, 0,
 1, 2, 0, 0),
(1007, 'db-server.example.com.h07', 'db-server.example.com', 'B', 'I', 2, 'E',
 '2026-05-11 07:41:00', '2026-05-11 07:43:00', '2026-05-11 07:45:00',
 0, 107, 2000002, 0, 0, 1, 0,
 1, 2, 0, 0),
(1008, 'db-server.example.com.h08', 'db-server.example.com', 'B', 'I', 2, 'T',
 '2026-05-18 07:41:00', '2026-05-18 07:43:00', '2026-05-18 08:03:00',
 0, 108, 2000002, 47000, 5046586572, 0, 0,
 1, 2, 0, 0),
(1009, 'files-server.example.com.h09', 'files-server.example.com', 'B', 'F', 3, 'T',
 '2026-04-27 07:41:00', '2026-04-27 07:46:00', '2026-04-27 11:26:00',
 0, 109, 2000003, 920000, 204010946560, 0, 0,
 2, 1, 0, 0),
(1010, 'files-server.example.com.h10', 'files-server.example.com', 'B', 'D', 3, 'T',
 '2026-05-04 07:41:00', '2026-05-04 07:45:00', '2026-05-04 08:41:00',
 0, 110, 2000003, 80000, 20132659200, 0, 0,
 1, 1, 0, 0),
(1011, 'files-server.example.com.h11', 'files-server.example.com', 'B', 'I', 3, 'T',
 '2026-05-11 07:41:00', '2026-05-11 07:45:00', '2026-05-11 08:11:00',
 0, 111, 2000003, 30000, 3006477107, 0, 0,
 1, 1, 0, 0),
(1012, 'files-server.example.com.h12', 'files-server.example.com', 'B', 'I', 3, 'T',
 '2026-05-18 07:41:00', '2026-05-18 07:45:00', '2026-05-18 08:09:00',
 0, 112, 2000003, 28000, 2952790016, 0, 0,
 1, 1, 0, 0),
(1013, 'app-server.example.com.h13', 'app-server.example.com', 'B', 'F', 4, 'T',
 '2026-04-27 07:41:00', '2026-04-27 07:43:00', '2026-04-27 08:41:00',
 0, 113, 2000004, 90000, 18253611008, 0, 0,
 2, 4, 0, 0),
(1014, 'app-server.example.com.h14', 'app-server.example.com', 'B', 'I', 4, 'T',
 '2026-05-04 07:41:00', '2026-05-04 07:43:00', '2026-05-04 07:51:00',
 0, 114, 2000004, 8000, 805306368, 0, 0,
 1, 4, 0, 0),
(1015, 'app-server.example.com.h15', 'app-server.example.com', 'B', 'I', 4, 'T',
 '2026-05-11 07:41:00', '2026-05-11 07:43:00', '2026-05-11 07:50:00',
 0, 115, 2000004, 7500, 751619276, 0, 0,
 1, 4, 0, 0),
(1016, 'app-server.example.com.h16', 'app-server.example.com', 'B', 'I', 4, 'T',
 '2026-05-18 07:41:00', '2026-05-18 07:43:00', '2026-05-18 07:49:00',
 0, 116, 2000004, 7000, 698351450, 0, 0,
 1, 4, 0, 0);

-- ─── Paths (depth 1-4 for jsTree) ─────────────────────────────────────────
-- pathid: 1=/var/log/  2=/var/log/nginx/  3=/etc/  4=/etc/nginx/
--         5=/var/lib/mysql/  6=/var/lib/mysql/data/  7=/var/lib/mysql/binlog/
--         8=/home/deploy/  9=/srv/data/  10=/srv/data/uploads/
--         11=/srv/data/backups/  12=/var/www/html/  13=/var/www/html/static/
--         14=/opt/app/  15=/opt/app/releases/  16=/backup/
INSERT INTO path (path) VALUES
('/var/log/'),
('/var/log/nginx/'),
('/etc/'),
('/etc/nginx/'),
('/var/lib/mysql/'),
('/var/lib/mysql/data/'),
('/var/lib/mysql/binlog/'),
('/home/deploy/'),
('/srv/data/'),
('/srv/data/uploads/'),
('/srv/data/backups/'),
('/var/www/html/'),
('/var/www/html/static/'),
('/opt/app/'),
('/opt/app/releases/'),
('/backup/');

-- ─── FileNames ─────────────────────────────────────────────────────────────
-- filenameid: 1=access.log  2=error.log  3=syslog  4=assets.tar.gz
--             5=ibdata1  6=ib_logfile0  7=ib_logfile1  8=mysql-bin.000001
--             9=database-dump.sql.gz  10=uploads.tar.gz  11=media-archive.tar.gz
--             12=backup-full.tar.gz  13=deploy.tar.gz  14=release.tar.gz  15=app.log
INSERT INTO filename (name) VALUES
('access.log'),
('error.log'),
('syslog'),
('assets.tar.gz'),
('ibdata1'),
('ib_logfile0'),
('ib_logfile1'),
('mysql-bin.000001'),
('database-dump.sql.gz'),
('uploads.tar.gz'),
('media-archive.tar.gz'),
('backup-full.tar.gz'),
('deploy.tar.gz'),
('release.tar.gz'),
('app.log');

-- ─── File records (jobs within last 24h → big_files jsTree) ────────────────
-- lstat position 7 = file size in Bacula base64
-- jobid=6
INSERT INTO file (fileindex, jobid, pathid, filenameid, markid, lstat, md5) VALUES
(1, 6, 2, 1, 0, 'bN Gj1 IiIf B A A A DIAAA KA IA BqBmIA BqBmIA BqBmIA A', '0'),
(2, 6, 2, 2, 0, 'bN Gj2 IiIf B A A A 8AAA KA IA BqBmIA BqBmIA BqBmIA A', '0'),
(3, 6, 1, 3, 0, 'bN Gj3 IiIf B A A A sAAA KA IA BqBmIA BqBmIA BqBmIA A', '0'),
(4, 6, 13, 4, 0, 'bN Gj4 IiIf B A A A GQAAA KA IA BqBmIA BqBmIA BqBmIA A', '0');

-- jobid=14
INSERT INTO file (fileindex, jobid, pathid, filenameid, markid, lstat, md5) VALUES
(1, 14, 5, 5, 0, 'bN Gj1 IiIf B A A A gAAAA KA IA BqBmIA BqBmIA BqBmIA A', '0'),
(2, 14, 6, 6, 0, 'bN Gj2 IiIf B A A A GQAAA KA IA BqBmIA BqBmIA BqBmIA A', '0'),
(3, 14, 6, 7, 0, 'bN Gj3 IiIf B A A A GQAAA KA IA BqBmIA BqBmIA BqBmIA A', '0'),
(4, 14, 7, 8, 0, 'bN Gj4 IiIf B A A A DIAAA KA IA BqBmIA BqBmIA BqBmIA A', '0'),
(5, 14, 16, 9, 0, 'bN Gj5 IiIf B A A A MgAAA KA IA BqBmIA BqBmIA BqBmIA A', '0');

-- jobid=22
INSERT INTO file (fileindex, jobid, pathid, filenameid, markid, lstat, md5) VALUES
(1, 22, 10, 10, 0, 'bN Gj1 IiIf B A A A gAAAA KA IA BqBmIA BqBmIA BqBmIA A', '0'),
(2, 22, 10, 11, 0, 'bN Gj2 IiIf B A A A MgAAA KA IA BqBmIA BqBmIA BqBmIA A', '0'),
(3, 22, 11, 12, 0, 'bN Gj3 IiIf B A A A GQAAA KA IA BqBmIA BqBmIA BqBmIA A', '0'),
(4, 22, 8, 13, 0, 'bN Gj4 IiIf B A A A DIAAA KA IA BqBmIA BqBmIA BqBmIA A', '0');

-- jobid=28
INSERT INTO file (fileindex, jobid, pathid, filenameid, markid, lstat, md5) VALUES
(1, 28, 15, 14, 0, 'bN Gj1 IiIf B A A A MgAAA KA IA BqBmIA BqBmIA BqBmIA A', '0'),
(2, 28, 14, 15, 0, 'bN Gj2 IiIf B A A A 8AAA KA IA BqBmIA BqBmIA BqBmIA A', '0'),
(3, 28, 1, 15, 0, 'bN Gj3 IiIf B A A A sAAA KA IA BqBmIA BqBmIA BqBmIA A', '0');

-- ─── JobMedia (link jobs to volumes) ──────────────────────────────────────
-- mediaid: 1-5=Daily-0001..0005  6-10=Weekly-0001..0005
INSERT INTO jobmedia (jobmediaid, jobid, mediaid, firstindex, lastindex,
                      startfile, endfile, startblock, endblock, volindex)
VALUES
(1, 1, 6, 1, 125000, 0, 0, 0, 4194304, 1),
(2, 2, 1, 1, 12000, 0, 0, 0, 409600, 1),
(3, 3, 1, 12001, 23500, 0, 0, 409601, 802816, 1),
(4, 4, 1, 23501, 34300, 0, 0, 802817, 1171456, 1),
(5, 5, 5, 34301, 43800, 0, 0, 1171457, 1499136, 1),
(6, 6, 5, 43801, 52000, 0, 0, 1499137, 1777664, 1),
(7, 7, 5, 52001, 57100, 0, 0, 1777665, 1941504, 1),
(8, 8, 7, 1, 280000, 0, 0, 0, 9175040, 1),
(9, 9, 5, 57101, 102100, 0, 0, 1941505, 3342336, 1),
(10, 10, 5, 102101, 102101, 0, 0, 3342337, 3342337, 1),
(11, 11, 5, 102102, 144100, 0, 0, 3342338, 4718592, 1),
(12, 12, 2, 144101, 192100, 0, 0, 4718593, 6291456, 1),
(13, 13, 2, 192101, 243100, 0, 0, 6291457, 7962624, 1),
(14, 14, 5, 243101, 287100, 0, 0, 7962625, 9404416, 1),
(15, 15, 8, 1, 950000, 0, 0, 0, 31457280, 1),
(16, 16, 5, 287101, 372100, 0, 0, 9404417, 12189696, 1),
(17, 17, 5, 372101, 404100, 0, 0, 12189697, 13238272, 1),
(18, 18, 3, 404101, 439100, 0, 0, 13238273, 14385152, 1),
(19, 19, 3, 439101, 439101, 0, 0, 14385153, 14385153, 1),
(20, 20, 3, 439102, 480100, 0, 0, 14385154, 15728640, 1),
(21, 21, 3, 480101, 518100, 0, 0, 15728641, 16973824, 1),
(22, 22, 5, 518101, 523300, 0, 0, 16973825, 17145856, 1),
(23, 23, 9, 1, 95000, 0, 0, 0, 3112960, 1),
(24, 24, 1, 523301, 531800, 0, 0, 17145857, 17424384, 1),
(25, 25, 1, 531801, 539800, 0, 0, 17424385, 17686528, 1),
(26, 26, 4, 539801, 547300, 0, 0, 17686529, 17932288, 1),
(27, 27, 4, 547301, 554300, 0, 0, 17932289, 18161664, 1),
(28, 28, 5, 554301, 560500, 0, 0, 18161665, 18366464, 1);

-- ─── Logs for warning/error jobs ──────────────────────────────────────────
INSERT INTO log (jobid, time, logtext) VALUES
(3, '2026-05-28 07:41:00', 'web-server.example.com-fd JobId 3: Warning: /var/log/syslog: file size shrunk by 1024 bytes; not saved.'),
(13, '2026-06-01 02:41:00', 'db-server.example.com-fd JobId 13: Warning: /var/lib/mysql/mysql-bin.000001: file changed.'),
(13, '2026-06-01 02:41:00', 'db-server.example.com-fd JobId 13: Warning: /var/lib/mysql/mysql-bin.000002: file changed.'),
(13, '2026-06-01 02:41:00', 'db-server.example.com-dir JobId 13: Warning: 3 files not saved due to file permission error.'),
(1003, '2026-05-11 07:41:00', 'web-server.example.com-fd JobId 1003: Warning: /var/log/auth.log: file size shrunk.'),
(1007, '2026-05-11 07:41:00', 'db-server.example.com-fd JobId 1007: Error: /var/lib/mysql/ibdata1: could not read.');

